### ISSUE TITLE
Circled BlurView

### ISSUE THREAD

**Issue by Shamilik** [react-native-community/react-native-blur#101]
Is there any way to set borderRadius for BlurView?

**Comment by Kureev** [comment]
It's inherited from RCTView, so should support a `borderRadius` style property. Have you tried that?

**Comment by Shamilik** [comment]
I did, but with no proper result.

**Comment by jakehasler** [comment]
I am also unable to apply a `borderRadius` supplying it in the style. Tried adding it manually in the package `src/BlurView.io.js` as well with no luck --

**Comment by breadadams** [comment]
I think this can be closed with the latest pr: https://github.com/react-native-community/react-native-blur/pull/119

**Comment by Kureev** [comment]
Thanks for the update, @breadadams
