### ISSUE TITLE
Not setting BlurAmount crashes app

### ISSUE THREAD

**Issue by rgovindji** [react-native-community/react-native-blur#103]
Updated to the latest version v1.1.0 and any page in my app that uses a BlurView crashes if the BlurAmount is not specified. 

This is the error I see:
`<_UIBackdropViewSettingsDark 0x7fc66ea24cc0> setNilValueForKey]: could not set nil as the value for the key blurRadius.'`

**Comment by zolar** [comment]
I am getting the same think with the latest RN 0.36.0 and v1.1.0.

**Comment by beast** [comment]
+1

**Comment by arthur31416** [comment]
Turns out blurAmount is now a prop:
```BlurView.propTypes = {
  blurType: PropTypes.string,
  blurAmount: PropTypes.number,
};```

Should we agree on a default prop for it ?

**Comment by Kureev** [comment]
`blurType` represents a type of blur, `blurAmount` represents a blur value (probably we should rename blurAmount to blurValue)

**Comment by Kureev** [comment]
@arthur31416 can you elaborate what you mean by "default props"?

**Comment by arthur31416** [comment]
In my case, the app is crashing in production if I don't provide a `blurAmount`. Once I give it, everything works like a charm.

So my suggestion is to give a default value for `blurAmount`, e.g. 10 so that there is no crash if it's not provided.

**Comment by Kureev** [comment]
@arthur31416 sure! Can you compose a PR?

**Comment by arthur31416** [comment]
@Kureev sure! Am I correct that is an iOS only feature? I'll go with a default value of 10 if it's alright.

**Comment by arthur31416** [comment]
Here is my PR: https://github.com/react-native-community/react-native-blur/pull/104

**Comment by Kureev** [comment]
Merged! Thanks for your contribution, @arthur31416! 👍

**Comment by Kureev** [comment]
Ah yeah, 1.1.1 has been released with this fix!

**Comment by rgovindji** [comment]
Awesome thanks @arthur31416 and @Kureev
