### ISSUE TITLE
BlurView inside a Modal with animationType='fade'

### ISSUE THREAD

**Issue by breadadams** [react-native-community/react-native-blur#105]
BlurView works great in a Modal with `animationType='slide'`, however if you use `fade`, there's a small pause before the background content is blurred. Any ideas?

**Comment by JonathanWi** [comment]
Same problem here also, although it's more a flickering before rendering the blurred content than a small pause for me

**Comment by breadadams** [comment]
Yeah, I guess I just phrased it wrong @JonathanWi, but that's basically what I see.

I launch my modal and it fades in, and say 1/2 a second later the content behind blurs. On closing modal however it **does** transition correctly (ie. there's no lag there).

**Comment by breadadams** [comment]
Nothing explains it better than a gif 😸 .

With `animationType='fade'`(didn't quite get the looping right here heh):

![blurview_modal_fade](https://cloud.githubusercontent.com/assets/5795227/19931339/75d20e1e-a10c-11e6-9ece-8cfe8e14e9d6.gif)

With `animationType='slide'`:

![blurview_modal_slide](https://cloud.githubusercontent.com/assets/5795227/19931386/98b938c6-a10c-11e6-84a9-82c3031403b1.gif)

**Comment by mastermoo** [comment]
i have a similar problem with a blurview component. it doesn't work as expected when animating its opacity.

**Comment by Kureev** [comment]
It works nicely with Animated and LayoutAnimation. Please, consider using one of them.

**Comment by isaacnass** [comment]
Yeah this is most definitely a valid issue.

**Comment by Leeds-eBooks** [comment]
I don't understand how people are getting this to work with LayoutAnimation. It doesn’t! You can really clearly tell this if you set slow animations on the iOS simulator. Has anyone really got this to work on iOS?

**Comment by zibs** [comment]
Alright, I was able to work around this by using https://github.com/oblador/react-native-animatable 

I set the modal to just use the `animationType='none'` setting, since this actually works with the blur view blurring immediately. I then fake the modal fade-in by using the AnimatedBlurView with an `animation='fadeIn'` property. 

```js

render () {
  <Modal
        animationType={'none'}
        transparent
        visible={this.props.visible}
        onRequestClose={() => {
          alert('Modal has been closed.');
        }}>
  <AnimatableBlurView
          useNativeDriver
          animation={'fadeIn'}
          duration={170}
          ref="blurredModal"
          blurType="xlight"
          blurAmount={20}
          style={{ flex: 1}}>

    </AnimatableBlurView>
  </Modal>
}
```

The problem was I also had to hack the fade-out as well - here I attach a ref to the animated blur view, which I then have a listener for when it should be dismissed. 
```js
  onPress={() => {
                this.refs.blurredModal.fadeOut(200).then(endState => {
                  // this method below actually hides the modal immediately, but since we have been fading out for 200ms it looks real.
                  this.props.fadeOutModal();
                });
              }}
```

Not great, but it worked for what I needed... I tried for a little bit with LayoutAnimation/Animated, and couldn't get it right, so I just went with this for now.

**Comment by AndyCrisan** [comment]
@zibs can you put a code for the full implementation ? 👍 please 🙏

**Comment by rahul120292** [comment]
just give background color to modal like      backgroundColor:"rgba(0,0,0,0.5)" , to blur background area .. no need to add any librabry to blur

**Comment by lsmolic** [comment]
@rahul120292 totally did NOT answer this question, but you got me where I wanted so ... enjoy your thumbs up and figurative Reddit Gold ⭐️

**Comment by mqlftw** [comment]
any fixes?
