### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by breadadams** [react-native-community/react-native-blur#106]
Tried to get the [example](https://github.com/react-native-community/react-native-blur#usage-example) working, but faced with 2 errors:

1. RCTWebSocket error: `Error: ignoring return value of function declared with warn_unused_result attribute`. Fixed with solution [here](https://github.com/facebook/react-native/issues/8584).

2. After fixing issue 1, I see the following in simulator:

![image](https://cloud.githubusercontent.com/assets/5795227/19908216/89c9dc9c-a082-11e6-8c54-1dc792dae99a.png)

**Comment by Kureev** [comment]
Examples are slightly outdated. We need to re-generate them using new react-native version

**Comment by breadadams** [comment]
I can create a pr with this if interested @Kureev

**Comment by Kureev** [comment]
That would be very nice!

**Comment by breadadams** [comment]
Sorted @Kureev, https://github.com/react-native-community/react-native-blur/pull/114 working nicely 😺
