### ISSUE TITLE
App crashing with BlurView

### ISSUE THREAD

**Issue by breadadams** [react-native-community/react-native-blur#107]
Sorry to bombard you with issues today 🙃, getting a crash when using `BlurView`, if I change it to `VibrancyView` it runs fine.

It *did* work for me a few times, but now I'm seeing this in Xcode console:

```
2016-11-01 22:35:02.188 myAppName[10120:558117] -[__NSCFNumber effectSettings]: unrecognized selector sent to instance 0xb0000000000000a3
2016-11-01 22:35:02.208 myAppName[10120:558117] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber effectSettings]: unrecognized selector sent to instance 0xb0000000000000a3'
```

Did a search in the project folder for `effectSettings` and I see it's being used in `/react-native-blur/ios/BlurAmount.m` - but I have no idea what that snippet does 😊 

Finally this is how I'm actually using it, just got the following inside a `<Modal>`:

```javascript
<BlurView
	blurType='light'
	blurAmount={10}
	style={styles.blurWrap}>

	// Inner components

</BlurView>
```

**Comment by JonathanWi** [comment]
Same issue here, did you update React Native recently by any chance?

**Comment by breadadams** [comment]
Nope @JonathanWi, had the same rn version since project started. @karolkozub has fixed it with this pr: https://github.com/react-native-community/react-native-blur/pull/108

**Comment by Kureev** [comment]
I think it may be related to the version of iOS you're trying to run this code (not sure tho)

**Comment by breadadams** [comment]
Running on iOS 10.1 @Kureev, you got an eta for when you're gonna merge #108?

**Comment by Kureev** [comment]
Merged
