### ISSUE TITLE
Orientation changes cause BlurView to re-blur

### ISSUE THREAD

**Issue by mathieu-gosbee-connectedlab** [react-native-community/react-native-blur#112]
Before:
![screen shot 2016-11-07 at 9 42 01 am](https://cloud.githubusercontent.com/assets/22594786/20061607/7e1c6cd4-a4ce-11e6-931b-510ba0fc04d4.png)

After:
![screen shot 2016-11-07 at 9 41 37 am](https://cloud.githubusercontent.com/assets/22594786/20061606/7e18fb58-a4ce-11e6-9a75-fab5877eaf57.png)

Orange is before orientation changes, Yellow is after.
This is the BlurView we are using.
```<BlurView blurType="light" blurAmount={20}>```

**Comment by StevenLambion** [comment]
I ran into the same issue.  I submitted a pull request with a possible fix for it:  #113

**Comment by Kureev** [comment]
Upgrading to 1.1.3 should solve the problem. Thanks again, @StevenLambion ❤️
