### ISSUE TITLE
':react-native-blur' could not be found in project ':app'.

### ISSUE THREAD

**Issue by emretekince** [react-native-community/react-native-blur#115]
I did rnpm link but still get this error: 
`Project with path ':react-native-blur' could not be found in project ':app'.`

**Comment by breadadams** [comment]
I presume you're getting this from `app/build.gradle`? Have you got `MainApplication.java` setup ([here](https://github.com/react-native-community/react-native-blur#troubleshooting))?

**Comment by emretekince** [comment]
I have just added this to settings.gradle:
```
include ':react-native-blur'
project(':react-native-blur').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-blur/android')
```
That error is gone but now I get:
```
Duplicate files copied in APK lib/armeabi-v7a/libblasV8.so
        File 1: \AppData\Local\Android\sdk\build-tools\23.0.1\renderscript\lib\packaged\armeabi-v7a\libblasV8.so
        File 2: \android\app\build\intermediates\exploded-aar\com.fivehundredpx\blurringview\1.0.0\jni\armeabi-v7a\libblasV8.so
```

**Comment by breadadams** [comment]
Hmm, you should be able to include with `compile project(':react-native-blur')`. Checkout the android code example [here](https://github.com/react-native-community/react-native-blur/tree/master/examples/Basic). Imported and working there on latest version of rn.

I think you're missing something from another project file, that and/or importing `react-native-blur` more than once.

**Comment by nomoreboredom** [comment]
FYI, using rn 0.37, react-native link missed one or two of the packages. Afterwards, rnpm link installed just the missing ones, but I had to add the reference to settings.gradle manually anyway.

**Comment by radical-edo** [comment]
@emretekince Have figured this problem out, I have the same issue, but can't make it work... :(

I've tried with `rnpm` but none of it seems to work. :(

**Comment by Kureev** [comment]
This is not a default scenario for `rnpm`. Seems we need to add an extra post-link step in this repo. Do anybody wants to pick it up?

**Comment by Kureev** [comment]
To fix libblasV8.so issue, consider removing
```
        renderscriptTargetApi 20
        renderscriptSupportModeEnabled true
```
from the `defaultConfig` section

**Comment by zareanmasoud** [comment]
I have just added this to `settings.gradle` and the error resolved.
```
include ':react-native-blur'
project(':react-native-blur').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/blur/android')
```
consider the address `../node_modules/@react-native-community/blur/android`
