### ISSUE TITLE
Content within BlurView is now blurred out

### ISSUE THREAD

**Issue by rgovindji** [react-native-community/react-native-blur#120]
React Native v0.28
react-native-blur v1.1.3

Upgraded to the latest version and now any content within a blurview is being blurred out as well as the image behind it.

```
      <Image 
        source={{uri: this.props.user.profilePhotoURL}}
        style={{width: width, height: width}}
       >
         <BlurView blurAmount={10} blurType="light" style={styles.container}>
              <Text> Hello World </Text>  /// This content is now being blurred out when it wasn't before
          </BlurView>
       </Image>
```

In the example above the text "Hello World" gets blurred out. It wasn't the case before

**Comment by Kureev** [comment]
Can you confirm that it still happening with 1.2.1?

**Comment by Kureev** [comment]
Just checked this one with React Native 0.40 and react-native-blur@2.0.0 - can't reproduce.

**Comment by elliotstokes** [comment]
This appears to still be happening with a VIbrancyView. BlurView works correctly though.

**Comment by zhllucky** [comment]
当内容为Image的时候，似乎被模糊了。
