### ISSUE TITLE
Duplicate files copied in APK lib/armeabi-v7a/libblasV8.so

### ISSUE THREAD

**Issue by fangzhen123** [react-native-community/react-native-blur#122]
Execution failed for task ':app:packageDebug'.
> Duplicate files copied in APK lib/armeabi-v7a/libblasV8.so
        File 1: D:\workspace\react-native\Ieasy\android\app\build\intermediates\exploded-aar\com.fivehundredpx\blurringview\1.0.0\jni\armeabi-v7a\libblasV8.so
        File 2: C:\Users\fangzhen\AppData\Local\Android\Sdk\build-tools\23.0.1\renderscript\lib\packaged\armeabi-v7a\libblasV8.so

why it works wrong? How can i solve it

**Comment by LiuuY** [comment]
Check your Android plug for Gradle, it should be 1.5.0 or later.

`buildscript {
    // ...
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0' // this should be 1.5.0 or higher
        // ...
    }
}`

**Comment by Arilas** [comment]
> Could not resolve all dependencies for configuration ':app:classpath'.
   > Could not find com.android.tools.build:gradle:1.5.0.
     Searched in the following locations:
         https://github.com/500px/500px-android-blur/raw/master/releases/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom
         https://github.com/500px/500px-android-blur/raw/master/releases/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.jar

After adding your line

**Comment by Kureev** [comment]
Seems this one can be closed
