### ISSUE TITLE
Blur not applied unless opacity is at 1

### ISSUE THREAD

**Issue by liamfd** [react-native-community/react-native-blur#126]
I'm currently using 1.2.0 and RN 0.37.0, and running ios 10.1 in the simulator. I noticed this first when I was attempting to run a transition, where I animated the opacity of a `View` that contains the `BlurView` and the blur just appeared when the transition was complete. In investigating, I found that it wasn't just the animation, it was that any opacity < 1  on the blur or its parent would prevent it from blurring.

For example, this shows a blur:
```javascript
<View style={{flexDirection: 'row'}}>
  <Image
    resizeMode="contain"
    source={{uri: 'https://placekitten.com/108/120'}}
    style={{width: 120, height: 108}} />
  <View style={{opacity: 1, position: 'absolute', left: 0, right: 0, top: 0, bottom: 0}}>
    <BlurView blurType="light" blurAmount={50} style={{flexGrow: 1}} />
  </View>
</View>
```

But the blur completely disapears when I change the inner `View` to:
```javascript
<View style={{opacity: 0.9, position: 'absolute', left: 0, right: 0, top: 0, bottom: 0}}>
  <BlurView blurType="light" blurAmount={50} style={{flexGrow: 1}} />
</View>
```
Notice the only difference is the opacity on the container of the second one. I tried moving the absolute positioning off of the containing `View` and that didn't help either.

This seems important, as as far as I can tell the recommended way to animate a blur view is to animate its container's opacity, so if that's not working, there's no way to animate it.

Please let me know if there's any other information I can provide.

**Comment by getreup** [comment]
hey @liamfd 

I've been struggling hard with this. It's not actually an issue with this library, but an issue with iOS itself. The way I fixed it is that I had to make sure the BlurView was not position:absolute.

So, if you need to blur things, make them absolute and behind the blurview, like this:

```
return (
<View style={{positon:'absolute', top:0, left:0, right:0, bottom:0>
  <Image
          style={{position:'absolute', left:0, right:0, top:0, bottom:0}}
          source={{uri: splashImageURI}}
        />
  <BlurView style={{flex:1, alignSelf:'stretch'}} />
</View>
)
```
Hopefully that helps.

**Comment by Kureev** [comment]
Hi @liamfd,

Can you check if @getreup solution can be applied to your case? If so, I would like to close this issue

**Comment by liamfd** [comment]
Hey @getreup, thanks for the help! Unfortunately, setting it up that way didn't help with the `opacity` issue specifically. Here's a more complete example of my issue, based on your code snippet:

```javascript
export default class TestBlurOpacity extends Component {
  constructor(props){
    super(props);
    this.state = { full_blur_visibility: true }
  }

  _handleOpacityToggle = () => {
    this.setState({full_blur_visibility: !this.state.full_blur_visibility})
  }

  render() {
    const { full_blur_visibility } = this.state;
    const blur_opacity = full_blur_visibility ? 1 : 0.9;

    return (
      <View style={{flex: 1}}>
        <View style={{position:'absolute', top:0, left:0, right:0, bottom:0}}>
          <Image
            style={{position:'absolute', left:0, right:0, top:0, bottom:0}}
            source={{uri: 'https://www.placecage.com/200/300'}} />
          <BlurView style={{flex:1, alignSelf:'stretch', opacity: blur_opacity}} blurType="dark" blurAmount={10} />
        </View>
        <Text style={{padding: 20}} onPress={this._handleOpacityToggle}>
          Toggle Opacity!
          Current Blur Opacity is {blur_opacity}.
        </Text>
      </View>
    );
  }
}
```

![blur_opacity_issues](https://cloud.githubusercontent.com/assets/5359538/20838219/92805f72-b875-11e6-9d50-53885a897bc3.gif)

You'll notice that it's toggling the opacity between `1` and `.9`, but the blur completely stops running at `opacity: 0.9`, whereas I'd expect it to just be slightly transparent.

Also, is @getreup's solution the only way to deal with absolute positioning? I'm attempting to make a drawer component so ideally the absolutely positioned thing would be the `BlurView`, and not the content it's overlaying.

**Comment by almirfilho** [comment]
Running into same issue here.
Any ideias on this? Thanks!

**Comment by Kureev** [comment]
Hey everybody. Sorry for taking a long time responding on it.
[According to the Apple docs about UIVisualEffectView](https://developer.apple.com/reference/uikit/uivisualeffectview) (which we use for blur on iOS): 
> When using the UIVisualEffectView class, avoid alpha values that are less than 1. Creating views that are partially transparent causes the system to combine the view and all the associated subviews during an offscreen render pass. UIVisualEffectView objects need to be combined as part of the content they are layered on top of in order to look correct. Setting the alpha to less than 1 on the visual effect view or any of its superviews causes many effects to look incorrect or not show up at all.

Therefore, it's not possible to apply opacity to the blur view due to Apple limitations.

**Comment by almirfilho** [comment]
That's interesting, since there are a bunch of apps (including some from Apple itself) that have some sort of fade in/out effect applied to blurviews. I wonder how they do it anyway...

**Comment by Kureev** [comment]
You can use LayoutAnimation / Animated (probably) to achieve this effect.

**Comment by Kureev** [comment]
see https://github.com/react-native-community/react-native-blur/issues/52 as a reference
