### ISSUE TITLE
only works inside of Image component

### ISSUE THREAD

**Issue by ochanje210** [react-native-community/react-native-blur#128]
```jsx
<Image source={src} style={styles.img}>
       <BlurView blurType="light" blurAmount={10} style={styles.blur}>
              <Text>Hi, I am a tiny menu item</Text>
       </BlurView>
</Image>
```
blurView works when you put it inside of react-native image component like the above. However it does not when you put it inside of View wrapper like below
```jsx
<View style={styles.container}>
       <BlurView blurType="light" blurAmount={10} style={styles.blur}>
              <Text>Hi, I am a tiny menu item</Text>
       </BlurView>
</View>
```

The module versions I am using:
    "react-native": "0.35.0"
    "react-native-blur": "1.2.0"

**Comment by getreup** [comment]
I believe this is an iOS limitation, not necessarily this library

**Comment by Kureev** [comment]
Just checked this issue in react-native@0.40 with react-native-blur@2.0.0 - it works in both cases.

**Comment by ochanje210** [comment]
Thank you!
