### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by CecilLee** [react-native-community/react-native-blur#132]
`Error: duplicate files during packaging of APK /Users/lichao/projects/bifu/android/app/build/outputs/apk/app-debug-unaligned.apk
	Path in archive: lib/armeabi-v7a/libblasV8.so
	Origin 1: /Users/lichao/Library/Android/sdk/build-tools/23.0.1/renderscript/lib/packaged/armeabi-v7a/libblasV8.so
	Origin 2: /Users/lichao/projects/bifu/android/app/build/intermediates/exploded-aar/com.fivehundredpx/blurringview/1.0.0/jni/armeabi-v7a/libblasV8.so
You can ignore those files in your build.gradle:
	android {
	  packagingOptions {
	    exclude 'lib/armeabi-v7a/libblasV8.so'
	  }
	}
:app:packageDebug FAILED

FAILURE: Build failed with an exception.
`

**Comment by Baransu** [comment]
I encountered the same error. I solved this by excluding given file as proposed in error message:
```
android {
  packagingOptions {
    exclude 'lib/armeabi-v7a/libblasV8.so'
  }
}
```

This may be caused by target SDK by this is only my guess

**Comment by jsochen** [comment]
I added, but it still wrong

**Comment by CecilLee** [comment]
grade 1.5.0 

ok
