### ISSUE TITLE
Examples not working under 1.2.1 (have to move back to 1.1.2)

### ISSUE THREAD

**Issue by opolyo01** [react-native-community/react-native-blur#135]
Basic/ios/build/Build/Intermediates/Basic.build/Debug-iphonesimulator/Basic.build/Objects-normal/x86_64/Basic_dependency_info.dat -o /Users/opolyako/tutorials/react-native-blur/examples/Basic/ios/build/Build/Products/Debug-iphonesimulator/Basic.app/Basic

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BlurAmount", referenced from:
      objc-class-ref in libRNBlur.a(BlurView.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:

	Ld build/Build/Products/Debug-iphonesimulator/Basic.app/Basic normal x86_64
(1 failure)

**Comment by elliotstokes** [comment]
I'm also seeing this error.

**Comment by skptl** [comment]
It is failing for 1.2.0 also, tried to go back to 1.2.0, but then had to revert back to 1.1.2.

**Comment by messense** [comment]
Same issue

**Comment by marcelkalveram** [comment]
Same here. Our builds started failing due to this error.

**Comment by patrickomeara** [comment]
hitting this issue as well. reverted back to 1.1.2.

**Comment by Maxim-Chugaev** [comment]
1.2.1 not work for me

**Comment by Kureev** [comment]
@Maxim-Chugaev please, consider opening a new issue describing what exactly doesn't work for you. Please, consider attaching code examples, steps to reproduce, error stack trace and everything you think may help to diagnose your issue.
