### ISSUE TITLE
Build Failure (iOS, RN 0.39) - React/RCTComponent.h file not found

### ISSUE THREAD

**Issue by adamterlson** [react-native-community/react-native-blur#141]
![image](https://cloud.githubusercontent.com/assets/2498418/21846177/2dad4114-d7f6-11e6-93db-a11fb5442173.png)

I get this build failure after:

```
npm install --save react-native-blur
react-native link react-native-blur
```

I have tried manual linking and other random things but haven't been able to solve this issue.  Any help appreciated!

**Comment by adamterlson** [comment]
Seems it has to do with the latest 2.0 path changes.  Will retry with an older version.

**Comment by adamterlson** [comment]
Reverting react-native-blur back to 1.2.0 fixes this issue.  1.3.0 was also a breaking change, it seems.

**Comment by Kureev** [comment]
Yeah, sorry for `1.3.0`. 
`1.2.1` is the last stable version for React Native < 0.40
