### ISSUE TITLE
Unpublish 1.3.0 from npm

### ISSUE THREAD

**Issue by f5io** [react-native-community/react-native-blur#143]
Hi guys, thanks for your fantastic work on the suite of tools you have for RN :)

Unfortunately, your version 1.3.0 which was published to npm contained breaking changes and broke our CI. I know this is most likely our fault for not hardening our dependencies, but we had `^1.1.2`. We have yet to go to RN 0.40. Foreseeing an influx of bug reports pertaining to this issue, it might be an idea to unpublish the 1.3.0 version from npm.

Thanks again for all the great stuff you guys are putting out.

**Comment by Kureev** [comment]
I have a strange npm error with unpublishing:
```
npm ERR! unpublish Failed to update data
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "unpublish" "react-native-blur@1.3.0"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code E500

npm ERR! "react-native-blur status = 403" : react-native-blur
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xamd/Projects/react-native-blur/npm-debug.log
```

Will try again later

**Comment by Kureev** [comment]
Blocked by https://github.com/npm/npm/issues/15531

**Comment by hilkeheremans** [comment]
Alternatively, you could publish an update to a higher version with the following trick:
```
#ifdef __has_include(<React/RCTBridge.h>)
#import <React/RCTBridge.h>
#import <React/RCTEventDispatcher.h>
#import "RNNotifications.h"
#import <React/RCTConvert.h>
#import <React/RCTUtils.h>
#else
#import "RCTBridge.h"
#import "RCTEventDispatcher.h"
#import "RNNotifications.h"
#import "RCTConvert.h"
#import "RCTUtils.h"
#endif
```

**Comment by Kureev** [comment]
Good one, actually. I can also re-publish 1.2.1 as 1.3.1 to avoid this issue.

**Comment by Kureev** [comment]
unpublished
