### ISSUE TITLE
Crash App

### ISSUE THREAD

**Issue by hungdev** [react-native-community/react-native-blur#145]
I dont know when i add <BlurView </BlurView> then reload app, it crash app. it say:" Unfortunately, BlurImage has stopped.
Can you fix it?
thanks you.

**Comment by alphasp** [comment]
if you are running on android, please refer example from https://github.com/react-native-community/react-native-blur/blob/master/examples/Basic/index.android.js, the api is different from ios example

**Comment by hungdev** [comment]
@alphasp  it still crash app.

**Comment by alphasp** [comment]
Were you able to run the [demo project](https://github.com/react-native-community/react-native-blur/blob/master/examples/Basic) successfully?
If you are running from your project, make sure you follow the instructions in readme that require you to run `react-native link react-native-blur` and add some config in `android/app/build.gradle` for android.

**Comment by hungdev** [comment]
i had run your example, it said error like this:
![er](https://cloud.githubusercontent.com/assets/12009276/22097904/2144d516-de56-11e6-97b2-2067141318d3.PNG)

**Comment by alphasp** [comment]
run `npm install react@15.3.1`

**Comment by hungdev** [comment]
thank you so much, your example ran. (y).

**Comment by hungdev** [comment]
@alphasp, i create new react native project, 
if i do step by step in the readme. then run, it says error like this:
![erd](https://cloud.githubusercontent.com/assets/12009276/22099806/71f2d1a8-de5f-11e6-8e74-435e9b1325a6.PNG)

but when i remove this lines
```
renderscriptTargetApi 20
renderscriptSupportModeEnabled true
```
 and do other steps then run it dont say error in the console but it will crashes app.
Can you solve it?

**Comment by alphasp** [comment]
Refer #122 
Check your `build.gradle` in android folder, it should be 1.5.0 or later.

`buildscript { dependencies { classpath 'com.android.tools.build:gradle:1.5.0' } }`

**Comment by hungdev** [comment]
@alphasp.  thank you so much. it worked. so great.

**Comment by hungdev** [comment]
@alphasp,i add classpath 'com.android.tools.build:gradle:1.5.0', it run fine. But when i add classpath 'com.android.tools.build:gradle:2.2.2' it say error 
![le](https://cloud.githubusercontent.com/assets/12009276/22104104/4db34b40-de70-11e6-9ad8-536fedcfbf26.PNG)

because my project run gradle 2.2.2.

**Comment by alphasp** [comment]
@hungdev I am not expert in gradle, but based on your error log, the minimum supported Gradle version is `2.14.1`, you can try to edit the distributionUrl to use gradle version `2.14.1` as per instruction or refer [http://stackoverflow.com/questions/34814368/gradle-version-2-10-is-required-error](http://stackoverflow.com/questions/34814368/gradle-version-2-10-is-required-error)

**Comment by hungdev** [comment]
@alphasp ,i look in the example
https://github.com/react-native-community/react-native-blur/blob/master/examples/Basic/android/build.gradle#L8

they are  using `2.2.2`.
I edited gradle to 2.14.1, it say error:
![ee](https://cloud.githubusercontent.com/assets/12009276/22105216/991d083c-de75-11e6-97cb-19a8bd594167.PNG)

**Comment by hungdev** [comment]
@Kureev , please fix it. i expect that.

**Comment by hungdev** [comment]
i solved my error.
i create new project, if i want to change classpath from 1.5.0 to 2.2.2 ( such as: https://github.com/react-native-community/react-native-blur/blob/master/examples/Basic/android/build.gradle#L8)
i must change this line distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip (default)
to distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
(such as: https://github.com/react-native-community/react-native-blur/blob/master/examples/Basic/android/gradle/wrapper/gradle-wrapper.properties#L6)
