### ISSUE TITLE
fatal error: 'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by roysG** [react-native-community/react-native-blur#150]
i Get error "fatal error: 'React/RCTViewManager.h' file not found" when the build failed

**Comment by jaredly** [comment]
What's your React Native version? This library requires 0.40.
Also, try turning off parallel builds in Xcode

**Comment by iskWang** [comment]
have same error in 0.37 :(

**Comment by Kureev** [comment]
If you're using < 0.40, make sure you use react-native-blur@1.2.1

**Comment by comur** [comment]
Hi @Kureev,
I have the same error since 2 days I'm trying to build without success
I'm on 0.48.4 and react-native-blur@3.2.0

**Comment by soundaraj2919** [comment]
anyone found the solution for that
