### ISSUE TITLE
Not working for Android

### ISSUE THREAD

**Issue by iiitmanikanta** [react-native-community/react-native-blur#177]
@Kureev When can we expect a release for Android?

**Comment by ndbroadbent** [comment]
Hi @iiitmanikanta, in the meantime you can point to my branch that works properly on both iOS and Android. You can add this to your `package.json`:

```
"react-native-blur": "ndbroadbent/react-native-blur#fix-ios",
```

Then you could subscribe to issue #174, and you should get an email when a new version is released.

**Comment by Kureev** [comment]
Please, try react-native-blur@3.0.0-alpha

**Comment by prasanth95** [comment]
@Kureev borderRadius is not working on Android
