### ISSUE TITLE
Blur amount is not respected in latest master

### ISSUE THREAD

**Issue by ligaz** [react-native-community/react-native-blur#179]
Hi there,

I'm testing the latest bits from the master branch and it looks like `blurAmount` property is not respected on iOS. It looks like the issue is from [this change](https://github.com/react-native-community/react-native-blur/commit/71b7e59a627370d3f7d04292777e0ad076a1c869#diff-84ac53a082ccd6040cfdc375b50698cf). 

@eliperkins Do you have an idea what might be wrong?

**Comment by Kureev** [comment]
latest commits are not released because I'm waiting for https://github.com/react-native-community/react-native-blur/pull/174 which solves the issue you're mentioning.

**Comment by ndbroadbent** [comment]
Hi @ligaz - in the meantime, you could point to my branch which works on both iOS and Android. You can add this to your `package.json`:

```
"react-native-blur": "ndbroadbent/react-native-blur#fix-ios",
```
