### ISSUE TITLE
iOS and Android Blur effect is not working

### ISSUE THREAD

**Issue by dileepkantapop** [react-native-community/react-native-blur#185]
Hi there,

    iOS and Android Blur effect and Vibrancy effect is not working.
To get the blur effect in Android i added every requirement for blur but it didn't even completed successful build.

**Comment by Kureev** [comment]
Please, try react-native-blur@3.0.0-alpha

**Comment by dileepkantapop** [comment]
Hi Kureev, 
    Thanks for your prompt reply. I have downloaded your git code and its working fine and I want to implement in my code its not working and in the terminal I am getting this error. Please check the attachment.
![screen shot 2017-04-18 at 10 57 45 am](https://cloud.githubusercontent.com/assets/5312091/25115802/2a3798b4-2426-11e7-8485-6b1194e30074.png)

**Comment by Kureev** [comment]
Interesting. I'll take a look! Sorry for the confusion. In the meantime, you may try to link it up manually

**Comment by dileepkantapop** [comment]
Hi Kureev,

    I am trying the same code with button click in android but I cannot see any change. Can you figure  out the solution
