### ISSUE TITLE
Android: support for dynamic content

### ISSUE THREAD

**Issue by StasDoskalenko** [react-native-community/react-native-blur#187]
Hi, everyone!
I've tried to use this component with dynamic content, eg. google maps. But I got only a semi-transparent view.

**Comment by itay9001** [comment]
Same here, even Text gets Semi-transparent for me,
Using 3.0Alpha

**Comment by roselind** [comment]
Has this problem been solved? I have the same problem。

**Comment by roselind** [comment]
It have  a  same problem  on example  .

 it's  blurview is not changed  when image changed

**Comment by StasDoskalenko** [comment]
@ndbroadbent Hi!
Thanks for such a great answer. If I find some workaround I'll do a PR :)

**Comment by itay9001** [comment]
Same thing happen on react-native-video, no solution for it as well?

**Comment by ndbroadbent** [comment]
Oh yeah, I don't think you would be able to blur a video unfortunately. It would work on iOS, but not Android. However, there might a different Android blurring library that could do this. I haven't looked into that

**Comment by hfllr** [comment]
stumbled accross this in 2023 now while trying to implement a glassmorphism-style navbar. It's still not working on android. Anyone has any fixes/alternatives by now?
