### ISSUE TITLE
[ANDROID] failed to find Build Tools revision 23.0.3

### ISSUE THREAD

**Issue by Fantasim** [react-native-community/react-native-blur#195]
Hi,

i'm currently trying to make work latest release on android but i handle this error when i'm compiling 

http://www.yagoshack.fr/?v=capturiqi.png

How can i fix that?

Thanks

**Comment by hgndggx** [comment]
![Uploading QQ图片20170505163820.png…]()

**Comment by hgndggx** [comment]
Download 23.0.3 in SDK manage ,then change buildToolsVersion in android/app/build.gradle

**Comment by Fantasim** [comment]
that's installed : 

http://www.yagoshack.fr/?v=capturtit.png

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.spottedwaysandroid"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 3
        versionName "1.2"
        renderscriptTargetApi 23
        renderscriptSupportModeEnabled true
        
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
....
```

i got same error
