### ISSUE TITLE
Blur Does not work

### ISSUE THREAD

**Issue by NeETsu** [react-native-community/react-native-blur#197]
Hello
we wanted to use the blurring bit sadly we where not able to recreate the blur effect. 
We Tried on a Photo, Text and on a Navigator and no one of them Worked.
These is the code we used:
```
if (this.state.appState.match(/inactive|background/)) {
        return(<View style={styles.container}>
          <Router
              backTitle = {backIcon}
              hideBackImage = "true"
              onLeft={() =>  DismissViewControllerManager.goBack()}
              leftTitle={backIcon}
              props={this.props.serverprops}
              navigationBarStyle = {{height:65, backgroundColor:'white'}}
              backButtonTextStyle = {{marginLeft: -6, marginTop: -9, height:35, color: Color,}}
              leftButtonTextStyle = {{marginLeft: 0, marginTop: -7, height:35, color: Color,}}
              titleStyle = {{fontSize:20, fontWeight:'500'}}
              scenes={scenes}/>
          <View style={styles.container}>
                  <View style={styles.blurContainer}>
                    <BlurView
                      blurType='xlight'
                      blurAmount={100}
                      style={[styles.blurView]} />
                      <Text style={[styles.text, { color: 'black' }]}>
                        Blur component (iOS)
                      </Text>
                  </View>
          </View>
      </View>);
}
```
The styles are exactly the same as by the example. We also tried to exchange the 'react-native-router-flux' navigator with an Image and with some Text but we where not able to get any blur.

Are we doing something wrong, or is the Blur not working?
Any help will be a Huge Help.

**Comment by Kureev** [comment]
Hi @NeETsu, why won't you start with our [example](https://github.com/react-native-community/react-native-blur/tree/master/examples/Basic)?

**Comment by NeETsu** [comment]
the example as it is is working fine
i updated my code to:
```
<View style={styles.container}>
            <Text style={styles.text}>
              Vibrancy component (iOS-only)
            </Text>
          <VibrancyView

            blurType='light'
            blurAmount={1}
            style={[styles.container, styles.blurContainer]}>
          </VibrancyView>
      </View>
```
what is the Minimum i need and in the example it is working
when i copy these to my project i don't get the VibrancyView as i would need it.
I went checking the logs and i get `Warning: Native component for "VibrancyView" does not exist`

The Solution for the Issue is only for Android. 
we are using the React native version 0.42.3

**Comment by Kureev** [comment]
this error indicates that you don't have a `VibrancyView.m` properly linked in the system. Did you run `react-native link react-native-blur` before running your code?

**Comment by NeETsu** [comment]
yes we done these. And still get the `Native component for "VibrancyView" does not exist` Warning

**Comment by Kureev** [comment]
Which version of the library / react-native do you use? Can you scaffold an example for me so I can take a look?

**Comment by NeETsu** [comment]
We use React 0.43.3 --> Made an update to same version as the Example --> still doesn't work
The Router is: 'react-native-router-flux'

The case we use it. We wan't to show a Blured Screen when the App is in the background.
```
class ReactNativeStarter extends React.Component {
   state = { appState: AppState.currentState }
   componentDidMount() { AppState.addEventListener('change', this._handleAppStateChange); }
   componentWillUnmount() { AppState.removeEventListener('change', this._handleAppStateChange); }
   _handleAppStateChange = (nextAppState) => {
     console.log('State is '+nextAppState);
     this.setState({appState: nextAppState});
   }

  render() {
      scenes.serverprops = this.props.serverprops;
      if (this.state.appState.match(/inactive|background/)) {
        return(<View style={styles.container}>
              <Text style={styles.text}>
                Vibrancy component (iOS-only)
              </Text>
            <VibrancyView

              blurType='light'
              blurAmount={1}
              style={[styles.container, styles.blurContainer]}>
            </VibrancyView>
        </View>);
      } else {
        return <Router
            backTitle = {backIcon}
            navigationBarStyle = {{height:65, backgroundColor:'white'}}
            titleStyle = {{fontSize:20, fontWeight:'500'}}
            scenes={scenes}/>
      }

    }
}
```
The Style component is a copy of the Example component

**Comment by ndbroadbent** [comment]
Hi @NeETsu - can you make sure that RNBlur is listed as a Library in your Xcode project?

![screen shot 2017-05-09 at 3 35 32 am](https://cloud.githubusercontent.com/assets/139536/26024572/2ce6cd28-37fe-11e7-88de-565107d672c5.png)

If not, you could try to add it manually, from `node_modules/react-native-blur/ios/RNBlur.xcodeproj`

**Comment by NeETsu** [comment]
Hello
yes we also have these listed in the Library but still do not get the Blur Effect
we can see a red frame around the field where the blur should be

**Comment by ndbroadbent** [comment]
@NeETsu Ah, the red frame means that RN cannot find this native module, so it is not being loaded properly. I'm sorry I can't be more help, but I would try to remove it from your project, then install it and re-run `react-native link`

**Comment by NeETsu** [comment]
We have solved the Issue.
the Problem was as written by you the missing native module
we needed to add the Module to the POD file

Thank you a lot for all the help
