### ISSUE TITLE
I can see gray background color but nothing is blurred

### ISSUE THREAD

**Issue by jvaclavik** [react-native-community/react-native-blur#200]
I still can't make the blur work. I can see the element but it has gray backround color if I use `blurType='light'` and it's black if I use `blurType='dark'`. Can you help me, please?

**Info about the project**
```
React native version 0.40
iOS 10.3
router: react-native-router-flux (I don't know if it's important but some of issues meantioned that)
```

**What I did:**
1. Install blur: `npm i --save react-native-blur`, 
2. Link it to project: `react-native link`
3. Close old npm server
4. Import lib and implementation
5. Clean project in XCode
6. New build in XCode
7. Set `backgroundColor: 'transparent'` of `BlurView` and its parent (I read about it in issues)

**Source code**
```
import { BlurView } from 'react-native-blur';

...

const styles = StyleSheet.create({
  blurView: {
    position: 'absolute',
    left: 50,
    right: 50,
    top: 50,
    bottom: 50,
    backgroundColor: 'transparent'
  },
})

...
const MyProfileScreen = (props) => {
  return (
    <MainContainer>
      <Section>
        <Profile
          avatarUrl={props.avatar && props.avatar.url}
          name={`${props.firstName} ${props.lastName}`}
          canEditAvatar
          onOpenActionSheet={() => { imagePicker.pickImage() }}
        />
      </Section>
     
      <BlurView
        style={styles.blurView}
        blurType='light'
        blurAmount={50}
      />
    </MainContainer>
  )
}

```

Here is the screenshot how it looks like:
![simulator screen shot 11 5 2017 15 30 42](https://cloud.githubusercontent.com/assets/858321/25951723/d211b1d8-365e-11e7-93ce-90c9a763d385.png)

**Comment by Kureev** [comment]
Do you have any ideas, @ndbroadbent?

**Comment by ndbroadbent** [comment]
Hi @jvaclavik, have you tried with a lower blur amount? 50 is very high, and might cause everything to be blurred into a solid gray. Although I'm not sure why the image and text would still be visible underneath. But I would recommend trying 10.

The blur on iOS is typically very stable, it's only Android that has been having some issues.

Try running the [Example app](https://github.com/react-native-community/react-native-blur#example-react-native-app) and comparing your code with that, you might have made a small typo somewhere.

**Comment by ndbroadbent** [comment]
Also, please confirm the version of `react-native-blur` that you are using.

**Comment by jvaclavik** [comment]
I tried example app but with the same result:
![simulator screen shot 16 5 2017 11 10 18](https://cloud.githubusercontent.com/assets/858321/26098609/98079c6e-3a28-11e7-9a87-ef0266e11b9d.png)

Version `3.0.0-alpha`

Change blur amount doesn't help. 
Should it work in iOS simulator?

**Comment by jvaclavik** [comment]
Aaaa, it works on device but not in iOS simulator! Thanks for your help!

**Comment by ndbroadbent** [comment]
Hi @jvaclavik that's very strange, it works on the iOS simulator for me. You might be using a MacBook with a different graphics chip, or a different version. Which version of iOS are you running in the simulator, what type of Mac, and which version of OS X?
