### ISSUE TITLE
Modules linked, but still getting red border

### ISSUE THREAD

**Issue by dmr07** [react-native-community/react-native-blur#208]
I'm aware there have been a number of issues on this already, but the solution of running `react-native link` has not worked for me as it did for others. The result is a red border outlining the area to be blurred.

After running `react-native link`, I get the following:
```
rnpm-install info Android module react-native-blur is already linked 
rnpm-install info iOS module react-native-blur is already linked
```

Is there anything else I should be doing?

React-Native: 0.45.0
React-Native-Blur: 3.0.0

**Comment by dmr07** [comment]
Didn't see step 5. Needed to rerun `react-native run-ios`

**Comment by jariwalabhavesh** [comment]
That fix it for me as well
