### ISSUE TITLE
Renderscript support mode problem (Android)

### ISSUE THREAD

**Issue by mnehal69** [react-native-community/react-native-blur#224]
Whenever i try to compile my app after following all steps it give me this error:

>*What went wrong:
>A problem occurred configuring project ':app'.
> Renderscript support mode is not supported with renderscript target 21+ in BuildTools 23.0.1
Please update to BuildTools 23.0.3 or above

But recently i update my android studio to new release and with that i update my android sdk  too but still getting this problem. What should i do?

**Comment by Kureev** [comment]
Hey @mnehal69!

I think this will help to solve your problem https://stackoverflow.com/questions/33155087/react-native-on-android-failed-to-find-build-tools
