### ISSUE TITLE
MapsPackage.java:27: error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by danieljgp2** [react-native-community/react-native-blur#228]
Hello, i'm trying to use MapView Component for android, i follow the step for andoird installation here [https://github.com/airbnb/react-native-maps/blob/master/docs/installation.md](url)  But everytime i try to run react-native run-android i get this build error 

> /home/jinx/Documents/rsdev/react/weather/node_modules/react-native-maps/lib/android/src/main/java/com/airbnb/android/react/maps/MapsPackage.java:27: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-maps:compileReleaseJavaWithJavac FAILED

I'm Using react 0.47.1

**Comment by ZeroCho** [comment]
Why do you post issues of react-native-maps here?
Anyway, that problem is solved in react-native-maps@0.16.0

**Comment by danieljgp2** [comment]
You are totally right, i'm sorry, and thanks
