### ISSUE TITLE
How to disable dark/light property

### ISSUE THREAD

**Issue by KatarinaSimnova** [react-native-community/react-native-blur#229]
I don't want my image to by lighter or darker. I don't want dark or light blurType. I just want the original color of my image. How to do that?

**Comment by Kureev** [comment]
Hi @KatarinaSimnova!

Not sure if this library can help you with this. On iOS, it depends on native implementation (see [here](https://www.raywenderlich.com/84043/ios-8-visual-effects-tutorial)) and on Android part it depends on a third-party library (which, actually, can blur without adding any kind of tint).

I believe you're looking for something generic, while this library is aiming to bridge missing API to RN. Hope it answers your questions.

**Comment by ThomasStubbe** [comment]
Also looking for this... Does anyone know a library that does that? I just want to blur the background without changing the colors to dark or light

**Comment by Kureev** [comment]
There are some libraries that re-implement the blur algorithm, but I'm afraid you'll have to port them manually

**Comment by C-odes** [comment]
I found a way around. You have to add overlayColor=""  to the <BlurView>
