### ISSUE TITLE
can i download or export the blurred image?

### ISSUE THREAD

**Issue by MoeMamdouh** [react-native-community/react-native-blur#244]

**Comment by Kureev** [comment]
Hi @MoeMamdouh!

Not sure what you mean by downloading/exporting here, but either way this library doesn't support any of these.

**Comment by MoeMamdouh** [comment]
thank you @Kureev
I mean make filter on image and use, like upload it to server.. just like Instgram

**Comment by Kureev** [comment]
I'm not aware if there are any libraries for react-native can cover your case. Most likely, you'll have to come up with your own native solution. You can blur an image using react-native-blur and then create a native module that takes view reference and makes a snapshot of it 🤔. Later on, you can send this snapshot to the server. But this is my wild guess.

**Comment by MoeMamdouh** [comment]
@Kureev thank you bro.
