### ISSUE TITLE
Native component for 'BlurView' does not exist

### ISSUE THREAD

**Issue by yy9306** [react-native-community/react-native-blur#260]
import { BlurView }  from 'react-native-blur';
```
render() {
  return (
        <BlurView blurType="light" blurAmount={50} style={styles.position}/>
   )
}
```
 
![1](https://user-images.githubusercontent.com/19721298/35255377-b35e46e4-0029-11e8-8ce9-808c85e0ff5b.jpg)

**Comment by Shamash2014** [comment]
Got the same error with react-native version 0.52

**Comment by ashleydw** [comment]
Solution in #249; add the libRNBlur.a manually to Build Phases

**Comment by Shamash2014** [comment]
Thanks @ashleydw !

**Comment by yy9306** [comment]
Thanks @ashleydw !
