### ISSUE TITLE
MainApplication.java:29: error: cannot find symbol new BlurViewPackage()

### ISSUE THREAD

**Issue by api182** [react-native-community/react-native-blur#263]
As the title says...

Unlinked and Uninstalled, then repeated installation, no joy... Opened in Android Studio and it says it can't load the package due to a .iml file missing?

**Comment by NicholasEli** [comment]
Also experiencing this.

**Comment by NicholasEli** [comment]
Solve with https://github.com/react-native-community/react-native-blur/issues/213
