### ISSUE TITLE
Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by rostyys** [react-native-community/react-native-blur#280]
Getting the following error:

![simulator screen shot - iphone x - 2018-07-24 at 14 19 58](https://user-images.githubusercontent.com/6425523/43166936-e6f2c4fa-8f4c-11e8-8017-aa8c84962e24.png)

My Code:

<img width="335" alt="screen shot 2018-07-24 at 2 22 40 pm" src="https://user-images.githubusercontent.com/6425523/43166982-10387e04-8f4d-11e8-8869-71db64197991.png">

**Comment by mangdin** [comment]
zhe same error.
