### ISSUE TITLE
'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by cao1034** [react-native-community/react-native-blur#282]
hi 
-> npm install react-native-blur --save 
-> react-native link react-native-blur
->cd ios
-> pod install 
![image](https://user-images.githubusercontent.com/11959771/43367779-3637be4e-9385-11e8-9bd2-c182bb57e8d8.png)

How can I not handle it?

**Comment by manuhook** [comment]
Hi, can tell me please how did you solve your problem ?
Thanks !

**Comment by cao1034** [comment]
hello, time is too long, remember that the cause of the problem has nothing to do with this project. So it was turned off directly.
Sorry！
