### ISSUE TITLE
Pixelated blur in Android 9

### ISSUE THREAD

**Issue by iagorm** [react-native-community/react-native-blur#314]
I'm facing a weird behavior on blur with Android 9, the blurAmount is set to 1 and type light, on emulators this works properly, on Android 9 physical device the blur is pixelated.

![Screenshot_2019-05-13-10-03-43-597_com rebellionpay rebellion pre](https://user-images.githubusercontent.com/13892132/57623690-a95bf200-7566-11e9-95c9-521e1febfc70.png)

**Comment by ptrocki** [comment]
Did you check, if this issue occur in https://github.com/500px/500px-android-blur ?

**Comment by iagorm** [comment]
Nope, so I created an [https://github.com/500px/500px-android-blur/issues/39](issue) there too as this wraps 500px, to see what happens.

**Comment by DaniCastel** [comment]
Do you have the property downsampleFactor, in your code? Try removing it or changing its value

**Comment by iagorm** [comment]
@DaniCastel I wasn't using this downsampleFactor, this situation occurs in specific OS Android 9, below that works perfectly.

**Comment by react-native-halcyon** [comment]
fixed mine by adding downsampleFactor with low value
Android 9

**Comment by iagorm** [comment]
As I don't have anymore this feature in my project, I can't test it.
