### ISSUE TITLE
Change DEPLOYMENT_TARGET back to iOS=8.0

### ISSUE THREAD

**Issue by grabbou** [react-native-community/react-native-blur#33]
> This identifies the earliest OS version on which your software can run.

I am targeting 8.0 and getting warnings:

> Object file (/Users/grabbou/Library/Developer/Xcode/DerivedData/este-fmrlxbyzjguqiohdnboycovvmxjd/Build/Products/Debug-iphonesimulator/libRNBlur.a(BlurViewManager.o)) was built for newer iOS version (9.0) than being linked (8.0)

Was there any specific decision behind that?

**Comment by Kureev** [comment]
Nope, we can rewind it back to 8.0! Wanna make a PR?

**Comment by grabbou** [comment]
I can do it, thanks :dancer: 

(We do support iOS9 only, but I have that feeling client will request iOS8 resulting in removing quick-actions support, but want to avoid warnings from side menu)

**Comment by Kureev** [comment]
So, any progress so far?

**Comment by grabbou** [comment]
Yes, I will get back on that today.

**Comment by Kureev** [comment]
It's a long day "today", isn't it? :smile:

**Comment by grabbou** [comment]
It is, indeed :dancer:

**Comment by 9mm** [comment]
So I'm kind of confused on this (and new to RN), will this work on iOS 7? Will it fail spectacularly or gracefully if its not?

**Comment by 9mm** [comment]
As a follow up question, how do I detect <= iOS 7 so I can fall back to something else (sweet library btw)

**Comment by Kureev** [comment]
yo @9mm! Unfortunately, it doesn't support iOS < 8, because it relies on [UIVisualEffects](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIVisualEffect_class/index.html#//apple_ref/occ/cl/UIVisualEffect).

**Comment by grabbou** [comment]
@9mm imo it's not worth it, but if you want to give it a go and send over PR - go for it. 

I would imagine, that we should change that method when target < 8 (https://github.com/react-native-fellowship/react-native-blur/blob/master/ios/BlurView.m#L7) and just display background with opacity (xlight = 0.2, light = 0.5, dark = 0.9) for instance.

**Comment by Kureev** [comment]
@grabbou I think it'll be more valuable if we can eventually rewrite this one in a favor of custom blur implementation we can share between iOS and Android

**Comment by grabbou** [comment]
I am not sure if there's any way to share custom blur implementation between Android & iOS. AFAIK there were few attempts back in the day to support blur effects on IOS prior to UIVisualEffects but I am not sure it's worth reinventing something, that works quite nice on system level and (hopefully) is well optimised.

**Comment by 9mm** [comment]
@grabbou  that is very interesting... great piece of information to know. Is there a way to detect iOS version in React Native, without the use of 3rd party libs?

**Comment by grabbou** [comment]
Yeah, if you are on Discord, ping me (same nickname) and I'll send you over some snippets tomorrow from work. I've done it in the past, just need to find it :)

**Comment by Kureev** [comment]
This one looks a bit outdated now.
