### ISSUE TITLE
 Task :@react-native-community_blur:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by jyotiprakash111** [react-native-community/react-native-blur#333]
#  Task :@react-native-community_blur:compileDebugJavaWithJavac FAILED

  "dependencies": {
    "@react-native-community/blur": "^3.3.1",
    "jetifier": "^1.6.4",
    "native-base": "^2.13.5",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-awesome-alerts": "^1.2.0",
    "react-native-fast-image": "^7.0.2",
    "react-native-fbsdk": "^1.0.3",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-google-signin": "^2.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-material-ripple": "^0.8.0",
    "react-native-modalbox": "^1.7.1",
    "react-native-phone-call": "^1.0.9",
    "react-native-qrcode": "^0.2.7",
    "react-native-vector-icons": "^6.6.0",
    "react-native-walkthrough-tooltip": "^1.0.1",
    "react-native-webview": "^7.0.2",
    "react-native-youtube": "^2.0.0-beta.1",
    "react-navigation": "^3.12.1"

**Comment by ThomasStubbe** [comment]
To append to this:

````BlurringView.java:10: error: package android.support.v8.renderscript does not exist
import android.support.v8.renderscript.Allocation;```

although 
```android.useAndroidX=true
android.enableJetifier=true``` 
is in gradle.properties

**Comment by msqar** [comment]
Any solution to this? no one replied yet and it was posted on Sept 7!

**Comment by asadadams** [comment]
@jyotiprakash111 did you please find a fix

**Comment by msqar** [comment]
@asadadams I fixed it by running `npx jetify`

**Comment by asadadams** [comment]
@msqar still the same error

**Comment by idolago94** [comment]
Any solution to this?

**Comment by fabriciosautner** [comment]
same problem
