### ISSUE TITLE
How to handle Background Notification by RNFirebase ? kindly help me.

### ISSUE THREAD

**Issue by jyotiprakash111** [react-native-community/react-native-blur#348]
#Question
<--
I want to play a notification Sound while receiving a notification from firebase. Anyone have ideas that how can we implement it ? #React-Native #React Native v60.5
 -->

**Comment by wmonecke** [comment]
This has nothing to do with react-native-blur.

**Comment by Psiiirus** [comment]
@jyotiprakash111 can you please close or delete this issue?
