### ISSUE TITLE
Cant install Version 3.5 via yarn

### ISSUE THREAD

**Issue by Psiiirus** [react-native-community/react-native-blur#362]
# Bug

Hi,
i don't really know why but yarn isn't picking up the latests version of 3.5, maybe a maintainer can have a quick look?

Thanks!

**Comment by danleveille** [comment]
I'm having this same issue, even if I try to add v3.5.0 specifically.

**Comment by mcarlier09** [comment]
Same for npm, any news when the version will be published?
How can I test the version 3.5 if I downlad this repo locally?

**Comment by wmonecke** [comment]
How is this repo so out of shape?

**Comment by Psiiirus** [comment]
> Same for npm, any news when the version will be published?
> How can I test the version 3.5 if I downlad this repo locally?

@mcarlier09 you can just add the repo with a selected commit to your packages...its something like:
`yarn add ssh://git@github.com:react-native-community/react-native-blur.git#e2075520c709caf3bb8cf8890fcbf9f96939c716`

**Comment by Windynik** [comment]
> yarn add ssh://git@github.com:react-native-community/react-native-blur.git#e2075520c709caf3bb8cf8890fcbf9f96939c716

@Psiiirus I tried the same, but then it said "Couldn't find any versions for "@react-native-community/blur" that matches "^3.5.0"

And i had to choose between 3.4.1, 3.3.1 & 3.3.0.

**Comment by Psiiirus** [comment]
@Windynik maybe I miss spelled something .
Try this https://stackoverflow.com/questions/43411864/how-to-install-package-from-github-repo-in-yarn

**Comment by Windynik** [comment]
@Psiiirus Yes! I finally fixed all those issues (that existed in 3.4.1)  and it works perfectly! Danke! :+1: 

I used `npm install https://github.com/react-native-community/react-native-blur.git\#e2075520c709caf3bb8cf8890fcbf9f96939c716`  which worked! ( I took the commit where the broken example was fixed. )

**Comment by CoenWarmer** [comment]
Question remains: why is `3.5.0` not available through NPM? @Kureev?

**Comment by NikolaMijovic93** [comment]
When will 3.5.0 be on npm ?

**Comment by NikolaMijovic93** [comment]
News: 3.6.0 is on NPM !
