### ISSUE TITLE
Add expo support

### ISSUE THREAD

**Issue by renanmav** [react-native-community/react-native-blur#381]
# Feature request

Add expo support. 

Followed install instructions on README (except linking) to install it on a sample app, and I got this error:

![Untitled-1](https://user-images.githubusercontent.com/43140758/82510536-2b1f1d80-9ae1-11ea-9369-8eb07ef85607.png)

cc @EvanBacon

**Comment by renanmav** [comment]
It would be good it this would add rn-web compatibility

**Comment by brunoaduarte** [comment]
@renanmav have you managed to make this library work with an expo project?

**Comment by renanmav** [comment]
@brunoaduarte nop :(

**Comment by EvanBacon** [comment]
Use `expo-blur` https://docs.expo.io/versions/latest/sdk/blur-view/ it has web support
