### ISSUE TITLE
Blurring of text?

### ISSUE THREAD

**Issue by niftylettuce** [react-native-community/react-native-blur#45]
It seems like images are only supported?

**Comment by niftylettuce** [comment]
Related to <https://github.com/react-native-fellowship/react-native-blur/issues/23#issuecomment-149887181> perhaps?

**Comment by Kureev** [comment]
Well, it works like a layer, so shouldn't matter what exactly you're blurring. Should work for a text also. Do you want an example for it?

**Comment by niftylettuce** [comment]
Yes please - I'm using this with `<Modal>` and `<Portal>` components for
Android/iOS respectively -- see React Native's docs for these, maybe you
can try to do an example using Modal on iOS simulator?  The text doesn't
blur :(

**Comment by grabbou** [comment]
Do you have issues with modals @niftylettuce ? I am using modals with that component and no issues so far. Anything in particular you might be interested in?

**Comment by niftylettuce** [comment]
I can't use Blur and Modal together, e.g. I have a Modal and I want to blur
everything behind it.

**Comment by grabbou** [comment]
That's what I am doing with native modal and it works w/o issues, so I think I could submit example with that.

**Comment by niftylettuce** [comment]
Please do, thank you!

**Comment by grittathh** [comment]
I was able to get the example to work (but, it's nowhere near as pretty as the screenshot you show in the readme. The vibrancy text, for instance, does not actually color relative to the background). I was not able to get this to work in my use case (I want to put a blur on top of a scrollView, and have it disappear whenever the scrollView is touched/scrolled).

**Comment by Kureev** [comment]
This issue looks a bit outdated. Should I just close it or any specific action should be taken here?

**Comment by Kureev** [comment]
Closed as outdated
