### ISSUE TITLE
Basic example didn't work: "Could not find dependencies"

### ISSUE THREAD

**Issue by lrettig** [react-native-community/react-native-blur#48]
I went into `examples/Basic` and ran `npm install`. I get the following error when I try to run the packager. The error is the same whether I run `npm start` or `react-native start`. Thanks.

```
$ npm start

> Basic@0.0.1 start /Users/foo/react-native-blur/examples/Basic
> node_modules/react-native/packager/packager.sh


Could not find dependencies.
Ensure dependencies are installed - run 'npm install' from project root.

$ npm -v
3.3.6
$ node -v
v5.0.0
$ react-native -v
react-native-cli: 0.1.10
react-native: 0.11.4
```

**Comment by Kureev** [comment]
Instead of fixing it for React-Native 0.11 I'd say we need to scaffold a new example for 0.19

**Comment by vstepanyuk** [comment]
doesn't work on 0.19

**Comment by stephensprinkle** [comment]
Just submitted a PR w/ a version bump of RN to 0.21.0 and ran great on my end.

**Comment by grabbou** [comment]
I think we should update this example to work just like in side-menu project -> https://github.com/react-native-fellowship/react-native-side-menu/blob/master/examples/Basic/package.json#L6 so that we always run version from master.
