### ISSUE TITLE
Is it possible to add transition animation when turning blur effect off?

### ISSUE THREAD

**Issue by seph14** [react-native-community/react-native-blur#52]
My use case is that I'm blurring the whole background view while a panel expands and transits to a new scene;
And when user goes back from the new scene, I want same thing happens - the panel shrinks and the blur goes away. 

If I apply LayoutAnimation while expanding the panel and adding the blur view, the blur effect does has a transition animation, but I don't how to apply the same effect while removing the blur view. 
Is there currently a possible way to do a nice blur -> plain view transition effect?

**Comment by Kureev** [comment]
Probably you can use an opacity property? (just a shot in the dark)

**Comment by shahen94** [comment]
@seph14 you can just wrap it in `Animated.View`

**Comment by aforty** [comment]
If anyone stumbles on this question, I achieved an unblurring effect by simply invoking `LayoutAnimation.easeInEaseOut()` when I changed the state that caused the `BlurView` to no longer be rendered.
