### ISSUE TITLE
not working under 0.26 and iOS

### ISSUE THREAD

**Issue by tuxtux00** [react-native-community/react-native-blur#76]
Hi there,

This module is not working for me.
As soon as I had the library under build phases, the app doesn't launch and stays on a blank screen without any helping message.

Is it happening to someone else ?

**Comment by Kureev** [comment]
Deployment target iOS8+?

**Comment by tuxtux00** [comment]
iOS8 yes

**Comment by Kureev** [comment]
Not sure it's anyhow related to the module itself then. Can you tell me why you think it is?

**Comment by tuxtux00** [comment]
As soon as I had the library under build phases, I get the blank screen.
If I remove it, everything works as excepted.

**Comment by Kureev** [comment]
No errors in the console? Just a blank screen?

**Comment by tuxtux00** [comment]
Nothing in Xcode and nothing in Chrome

**Comment by Kureev** [comment]
I think I need to see a code snippet. Otherwise I have no nothing to start with. My guess is that something went wrong during the linking process. I'd recommend you to use `rnpm link` or `react-native link` (0.29+).

I can confirm that everything works on 0.26 for a new project with a proper linking.

**Comment by tuxtux00** [comment]
Yes it is obviously difficult to debug.
I will try using rnpm or react-native link and and I will let you know what happens.

Thanks for your time

**Comment by tuxtux00** [comment]
Hi there,
after upgrading to rn 0.30, I confirme that it is working as it sould.

**Comment by cmcewen** [comment]
Great!
