### ISSUE TITLE
BlurView does not blur the image

### ISSUE THREAD

**Issue by akd6162** [react-native-community/react-native-blur#77]
I am using BlurView Component ..But there is not blurring in the image
It gives the warning that Native Component for BlurView does not exist. What should I do now..?

**Comment by Kureev** [comment]
1) `npm list | grep react-native` to get your react-native version
2) Check if native dependencies has been linked according to the repo's README (or by using `rnpm link` or `react-native link` if you're using react-native > 0.29).
3) Show stack trace of error / screenshots

**Comment by akd6162** [comment]
![screenshot from 2016-08-05 11 18 31](https://cloud.githubusercontent.com/assets/20638847/17427465/80d88a94-5afe-11e6-93fb-de37c980606b.png)

**Comment by akd6162** [comment]
In bottom of this app page I got a warning Native Component for BlurView does not exist

**Comment by akd6162** [comment]
and one more thing I am using react native 0.29

**Comment by Kureev** [comment]
Did you follow README instructions? https://github.com/react-native-community/react-native-blur#android

**Comment by pz789as** [comment]
BlurView can't working in ipad2 Simulator

**Comment by akd6162** [comment]
yeah ...@Kureev

**Comment by Kureev** [comment]
@pz789as it works if you have a build target > 8.0 (see README)

**Comment by Kureev** [comment]
@akd6162 everything compiles, but you still see the same warning?

**Comment by Kureev** [comment]
cc @cmcewen

**Comment by akd6162** [comment]
@Kureev  Yes

**Comment by cmcewen** [comment]
Is this in a new project or running in the `Examples` folder?

**Comment by akd6162** [comment]
@cmcewen  on actually it is a demo project...just to know how  blur the Image

**Comment by siwananda** [comment]
@cmcewen @kureev @akd6162 not sure if this is helpful as several days have lapsed.

Seems like BlurViewPackage needs to be included in the android side of things.

Depending on your RN version, the change need to be done in either MainActivity.java or MainApplication.java.

```java
import com.cmcewen.blurview.BlurViewPackage;

public class MainApplication extends Application implements ReactApplication {
...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(), new BlurViewPackage()
      );
    }
```

This exists in the example folder but not mentioned in the readme.

**Comment by cmcewen** [comment]
@siwananda if you run `rnpm link` or `react-native link` on newer versions of RN that should be added automatically. It's mentioned in the installation section but feel free to PR a change to the docs you think would make it more clear

**Comment by siwananda** [comment]
@cmcewen You're right, on a newer install, `rnpm link` does add the package as well. Submitted a PR anyways since this bit me before. Thanks!
