### ISSUE TITLE
Ability to blur views?

### ISSUE THREAD

**Issue by romanchukenator** [react-native-community/react-native-blur#79]
As I understand it this is primarily used to blur images. Any way to blur <View> tags?

**Comment by Kureev** [comment]
Could you be so kind to explain me what do you mean by tags?

**Comment by romanchukenator** [comment]
I just mean to blur content in, say, a ```<View>```.

Say I have a 
```javascript
<View style={styles.viewStyle}>
  <Text>Random interesting text</Text>
    <CustomComponent
      attribute1={this.props.attr1}
      attribute2={this.props.attr2}
    
      attributeId={this.props.attrId}
  />

  <BlurView blurType="light" style={styles.blur}>
    <Text>Text I do not want blurred</Text>
  </BlurView>
</View>
```

Is there a way to make everything in the ```<View>``` tag blurred while the the text isn't? I'm assuming not, but just in case I thought I'd ask.

**Comment by cmcewen** [comment]
Probably easiest to use `{position: 'absolute'}` on the Text and stick it outside the tag so you can overlay it on the blurred content. So it would look like
```
<View>
  <BlurView>
    <View style={styles.viewStyle}>
    ...
    </View>
  </BlurView>
  <Text style={styles.absoluteText}>I do not want to be blurred</Text>
</View>
```
