### ISSUE TITLE
BlurringView cannot be cast to android.view.ViewGroup

### ISSUE THREAD

**Issue by shahen94** [react-native-community/react-native-blur#84]
I tried to use this, but kept getting errors
` <BlurView blurType="dark" style={styles.absolute}>
   <View style={styles.absolute}>
        ......something here
  </View>
</BlurView>`

**Comment by tuneZola** [comment]
@shahen94 I am getting the same thing, did you ever resolve the issue?

**Comment by shahen94** [comment]
@tuneZola yes.
Just for android syntax is a little bit different.
For android you should write

`<BlurView viewRef={this.state.viewRef}>`
And then 
`<Image source... ref={this.setViewRef}>`
`setViewRef(ref) {
    this.setState({
         viewRef: findNodeHandle(ref)
   });
}`

**Comment by tuneZola** [comment]
@shahen94 Thanks, I will try that out.

**Comment by shahdghorsi** [comment]
Hello @shahen94 I'm trying to set a WaveLoadingView on my Android but I'm getting this error and I couldn't fix it:
  Caused by: android.view.InflateException: Binary XML file line #0: me.itangqi.waveloadingview.WaveLoadingView cannot be cast to android.view.ViewGroup
                                                                                 Caused by: java.lang.ClassCastException: me.itangqi.waveloadingview.WaveLoadingView cannot be cast to android.view.ViewGroup

**Comment by shahdghorsi** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context="com.example.recodedharran.test.MainActivity">


        <me.itangqi.waveloadingview.WaveLoadingView
            android:id="@+id/wave_loading_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:wlv_borderColor="@color/colorAccent"
            app:wlv_borderWidth="3dp"
            app:wlv_shapeType="circle"
            app:wlv_round_rectangle="true"
            app:wlv_triangle_direction="north"


            app:wlv_titleCenterStrokeColor="@color/colorTransperant"
            app:wlv_titleCenterStrokeWidth="3dp"
            app:wlv_titleCenterColor="@color/colorWhite"
            app:wlv_titleCenterSize="24sp"



            app:wlv_titleTopStrokeColor="@color/colorTransperant"
            app:wlv_titleTopStrokeWidth="3dp"
            app:wlv_titleTopColor="@color/colorWhite"
            app:wlv_titleTopSize="24sp"


            app:wlv_titleBottomStrokeColor="@color/colorTransperant"
            app:wlv_titleBottomStrokeWidth="3dp"
            app:wlv_titleBottomColor="@color/colorWhite"
            app:wlv_titleBottomSize="24sp"
            app:wlv_waveAmplitude="70"
            app:wlv_waveColor="@color/colorAccent">

            <SeekBar
                android:id="@+id/seek_bar"
                android:max="100"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"

                />



        </me.itangqi.waveloadingview.WaveLoadingView>

    </LinearLayout>


`

**Comment by shahdghorsi** [comment]
`package com.example.recodedharran.test;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.SeekBar;

import butterknife.BindView;
import butterknife.ButterKnife;
import me.itangqi.waveloadingview.WaveLoadingView;

public class MainActivity extends AppCompatActivity {

    //@BindView(R.id.seek_bar)
    //SeekBar seekBar;
    //@BindView(R.id.wave_loading_view)
   // WaveLoadingView waveLoadingView;
    WaveLoadingView waveLoadingView;
    SeekBar seekBar;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        //ButterKnife.bind(this);
        waveLoadingView=(WaveLoadingView) findViewById(R.id.wave_loading_view);
        seekBar=(SeekBar) findViewById(R.id.seek_bar);
        waveLoadingView.setProgressValue(0);
        seekBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                waveLoadingView.setProgressValue(progress);
                if(progress<50){
                    waveLoadingView.setBottomTitle(String.format("%d%%",progress));
                    waveLoadingView.setCenterTitle("");
                    waveLoadingView.setTopTitle("");

                }
                else if(progress<80){
                    waveLoadingView.setBottomTitle("");
                    waveLoadingView.setCenterTitle(String.format("%d%%",progress));
                    waveLoadingView.setTopTitle("");
                }
                else {

                    waveLoadingView.setBottomTitle("");
                    waveLoadingView.setCenterTitle("");
                    waveLoadingView.setTopTitle(String.format("%d%%",progress));
                }
            }



            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {

            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {

            }
        });


    }

}`

**Comment by RameshSain** [comment]
Add the zIndex in style 9999999999 and add it in superview after mapview

**Comment by shahdghorsi** [comment]
Thank you so much
