### ISSUE TITLE
Blur intensity

### ISSUE THREAD

**Issue by jpolack** [react-native-community/react-native-blur#86]
Hello everyone,

i am using the Module to make text temporary unreadable.
While doing so i noticed that the blur effect ist quite heavy.

Is there a property to adjust the bluriness?
If not that would be a very nice feature! 

Thanks in advance

Jonah

**Comment by tuxtux00** [comment]
Hi there,

+1 for this feature

**Comment by roysG** [comment]
+1

**Comment by Kureev** [comment]
As far as I know Apple doesn't provide any ways to adjust blur value. I remember somebody told me that they use opacity for this purpose. Can you check if it can be used?

**Comment by jonzee** [comment]
BlurView looks strange with opacity, on lower opacity (0.5) we can see horizontal stripes
- opacity: 0.5
![simulator screen shot 30 wrz 2016 15 23 47](https://cloud.githubusercontent.com/assets/9372463/18993098/f28cd29a-8721-11e6-90fa-45913a671490.png)

- opacity: 0.95
![simulator screen shot 30 wrz 2016 15 22 42](https://cloud.githubusercontent.com/assets/9372463/18993114/ff85b4da-8721-11e6-9adb-86b8b3adab5a.png)

**Comment by jakehasler** [comment]
I just submitted a PR (#102) that solves this problem. Feel free to check it out!

**Comment by Kureev** [comment]
As far as https://github.com/react-native-community/react-native-blur/pull/102 has been merged and released, I'm going to close this issue.
