### ISSUE TITLE
How to use blur component for Android

### ISSUE THREAD

**Issue by cdmalcl** [react-native-community/react-native-blur#89]
running on Android: examples/Basic 0.8.0 
just like this:
![image](https://cloud.githubusercontent.com/assets/8749073/18084678/ae7589f8-6eda-11e6-8d8f-968b15e6a615.png)

How can I get a result like this effect？：
https://github.com/500px/500px-android-blur

**Comment by Kureev** [comment]
cc @cmcewen

**Comment by cmcewen** [comment]
@cdmalcl try changing the overlay color alpha or the blur radius to change the effect

**Comment by cdmalcl** [comment]
I did, not just like the right effect. And the blur radius, no change after the change.

**Comment by Kureev** [comment]
Hey guys! Seems that nothing happens in this issue for more than two months. I'm about to close it for now. Feel free to re-open it if needed.
