### ISSUE TITLE
iOS 10 support

### ISSUE THREAD

**Issue by generalChaos** [react-native-community/react-native-blur#92]
The blur effect does not work on the newly released iOS 10.

**Comment by Kureev** [comment]
Did they changed API?

**Comment by generalChaos** [comment]
Thanks for the hard work on this module and sorry for the lack of description in the issue report, I am not very familiar with iOS API.  I did notice that the blur was gone on clients running iOS 10.

I have found documentation of the changes in the API: https://developer.apple.com/library/content/releasenotes/General/iOS10APIDiffs/  

Looking at the Swift UIKit, they seemed to have made some changes to that: https://developer.apple.com/library/content/releasenotes/General/iOS10APIDiffs/Swift/UIKit.html

Thanks

**Comment by merapi** [comment]
@generalChaos it only breaks on 10.0.1 right? testing it on simulator (iphone6&7 10.0):

![ios10](https://photos-1.dropbox.com/t/2/AABm8xwl2h2CeG5JQnTqdyOo6PX_wdAYfe7eOPtSQRJh8g/12/600833953/png/32x32/3/1474470000/0/2/Screenshot%202016-09-21%2012.49.25.png/EPvLme0EGB4gAigC/SgvHA3_46X3_9vGkU3AxKAT-OE7gZ727RhetctACP2Y?size_mode=3&dl=0&size=800x600)

**Comment by Kureev** [comment]
Did you try it on 10.0.1 as well, @merapi ?

P.S. Thanks for the testing!

**Comment by merapi** [comment]
there is no simulator for 10.0.1 and my device doesn't have that update also

**Comment by generalChaos** [comment]
@merapi It's not working on the iOS 10 simulator and my phone running iOS 10.1.  I am going to check my implementation to make sure the problem is not with that.  The way I have it, works with iOS < 10.  Thanks.

**Comment by generalChaos** [comment]
@Kureev Sorry for the false alarm, I had a style which was breaking it for iOS10+. As soon as I test on iOS 10.1, I'll let you know the result.  However, I expect that it will still work.

**Comment by Kureev** [comment]
Awesome! I'm glad to hear you solved your issue and it's not related to this component. Let me know if something will pop up!

**Comment by generalChaos** [comment]
@Kureev, @merapi - I have tested it on 10.1 and it IS working. Sorry again for the false alarm.  Cheers, Rico
